module.exports = (app) => {
  let authRoute = require("./auth.routes");
  let uploadRoute = require("./upload.routes");
  let categoryRoute = require("./category/category.route");
  let formRoute = require("./form/form.route");
  let employeeRoute = require("./employee/employee.routes");
  let companyRoute = require("./company/company.routes");
  let mainPageRoute = require("./landingPage/mainPage.routes");
  let modulesRoute = require("./landingPage/modules.routes");
  let subModulesRoute = require("./landingPage/subModules.routes");
  let questionRoute = require("./landingPage/question.routes");
  let contactUsRoute = require("./pages/contactUs.routes");
  let aboutUsRoute = require("./pages/aboutUs.routes");
  let teamRoute = require("./pages/team.routes");
  let planRoute = require("./subscription/plan.routes");
  let couponRoute = require("./subscription/coupon.routes");
  // let registrationRoute = require("./subscription/registration.routes");
  let customerRoute = require("./staticFormData/customer.routes");
  let siteRoute = require("./staticFormData/site.routes");
  // let componentRoute = require("./form/component.routes");
  // let subComponentRoute = require("./form/subComponent.routes");
  let licenceRoute = require("./form/licence.routes");
  let tradeCategoryRoute = require("./form/tradeCategory.routes");
  let jobTaskRoute = require("./form/jobTask.routes");
  let companyDetailRoute = require("./subscription/companyDetail.routes");
  let portalRoute = require("./faq/portal.routes");
  let faqRoute = require("./faq/faq.routes");
  let projectManagerRoute = require("./projectManager/projectManager.routes");
  let riskRoute = require("./form/risk.routes");
  let ppeRoute = require("./form/ppe.routes");
  let copRoute = require("./form/cop.routes");
  let identifyHazardRoute = require("./form/identifyHazard.routes");
  let controlActionRequiredRoute = require("./form/controlActionRequired.routes");
  let jobNumberRoute = require("./form/jobNumber.routes");
  let jurisdictionRoute = require("./form/jurisdiction.routes");
  let safetyLegislationRoute = require("./form/safetyLegislation.routes");
  let regulatorRoute = require("./form/regulator.routes");
  let chemicalRoute = require("./form/chemical.routes");
  let riskLevelRoute = require("./form/riskLevel.routes");
  let residualRiskRoute = require("./form/residualRisk.routes");
  let staffRoute = require("./form/staff.routes");
  let stateRoute = require("./form/state.routes");
  let stripeAPIRoute = require("./Stripe/stripeAPI.routes");
  let ourWorkRoute = require("./pages/ourWork.routes");
  let socialMediaRoute = require("./pages/socialMedia.routes");
  let toolboxRoute = require("./toolbox/toolbox.routes");
  let meetingMinutesRoute = require("./meetingMinutes/meetingMinutes.routes");// meeting minuets
  let siteInspectionRoute = require("./form/siteInspection.routes");
  let vehicleInspectionRoute = require("./vehicleInspection/vehicleInspection.routes"); // vehicle inspection
  let hazardRoute = require("./form/hazard.routes");
  let incidentFormRoute = require("./form/incidentForm/incidentForm.routes");
  let changesMadeRoute = require("./form/incidentForm/changesMade.routes");
  let natureOfIncidentRoute = require("./form/incidentForm/natureOfIncident.routes");
  let rootcauseOfIncidentRoute = require("./form/incidentForm/rootcauseOfIncident.routes");
  let typeOfIncidentRoute = require("./form/incidentForm/typeOfIncident.routes");
  let managerRoute = require("./form/manager.routes");
  let WHSManagerRoute = require("./form/WHSManager.routes");
  let siteInspectionCategoryRoute = require("./form/siteInspectionCategory/siteInspectionCategory.routes");
  let siteInspectionTopicRoute = require("./form/siteInspectionCategory/siteInspectionTopic.routes");
  let hazardTreatmentRelationRoute = require("./form/hazardTreatmentRelation.routes");
  let riskAssessmentRoute = require("./form/riskAssessment.routes");
  let roleRoute = require("./subscription/role.routes");
  let accessRoute = require("./subscription/access.routes");
  let submittedDynamicFormRoute = require("./form/submittedDynamicForm.routes");
  let savedFormsRoute = require("./form/savedForms/savedForms.routes");
  let savedDynamicFormRoute = require("./form/savedDynamicForm.routes");
  let formCategoryRoute = require("./form/formCategory.routes");
  let accidentReportInstructionRoute = require("./form/accidentReportInstruction.routes");
  let riskAsstInstructionRoute = require("./form/riskAsstInstruction.routes");
  let subContractorRoute = require("./subContractor/subContractor.routes");
  let termsAndConditionRoute = require("./form/termsAndCondition/termsAndCondition.routes");
  let plantReturnRoute = require("./return/plantReturn/plantRetun.routes");
  let ppeReturnRoute = require("./return/ppeReturn/ppeReturn.routes");
  let sendMailRoute = require("./sendmail/sendmail");
  let logicalFormFrequencyRoute = require("./form/logicalFormFrequency.routes");
  let registrationlnCmsRoute = require("./pages/registrationlnCms.routes");
  let subscriptionCmsRoute = require("./pages/subscriptionCms.routes");
  let dashboardRoute = require("./dashboard/dashboard.routes");
  let notificationRoute = require("./notification/notification.routes");
  let departmentRoute = require("./subscription/department.routes");
  let itemsRoute = require("./registers/items.routes");
  let branchRoute = require("./subscription/branch.routes");
  let formSetting = require("./formSetting/formSetting.routes.js")

  
  const auth = require("../helper/auth");


  app.use("/api/v1/authentication", authRoute);
  app.use("/api/v1/upload", uploadRoute);
  app.use("/api/v1/category", categoryRoute);
  app.use("/api/v1/form", formRoute);
  app.use("/api/v1/employee", employeeRoute);
  app.use("/api/v1/company", companyRoute);
  app.use("/api/v1/mainPage", mainPageRoute);
  app.use("/api/v1/module", modulesRoute);
  app.use("/api/v1/subModule", subModulesRoute);
  app.use("/api/v1/question", questionRoute);
  app.use("/api/v1/contactUs", contactUsRoute);
  app.use("/api/v1/aboutUs", aboutUsRoute);
  app.use("/api/v1/team", teamRoute);
  app.use("/api/v1/plan", planRoute);
  app.use("/api/v1/coupon", couponRoute);
  // app.use("/api/v1/registration", registrationRoute);
  app.use("/api/v1/customer", auth, customerRoute);
  app.use("/api/v1/site", auth, siteRoute);
  // app.use("/api/v1/component", componentRoute);
  // app.use("/api/v1/subComponent", subComponentRoute);
  app.use("/api/v1/licence", auth, licenceRoute);
  app.use("/api/v1/tradeCategory", auth, tradeCategoryRoute);
  app.use("/api/v1/jobTask", auth, jobTaskRoute);
  app.use("/api/v1/companyDetail", companyDetailRoute);
  app.use("/api/v1/portal", portalRoute);
  app.use("/api/v1/faq", faqRoute);
  app.use("/api/v1/projectManager", auth, projectManagerRoute);
  app.use("/api/v1/risk", riskRoute);
  app.use("/api/v1/ppe", auth, ppeRoute);
  app.use("/api/v1/cop", copRoute);
  app.use("/api/v1/identifyHazard", identifyHazardRoute);
  app.use("/api/v1/controlActionRequired", auth, controlActionRequiredRoute);
  app.use("/api/v1/jobNumber", jobNumberRoute);
  app.use("/api/v1/jurisdiction", jurisdictionRoute);
  app.use("/api/v1/safetyLegislation", safetyLegislationRoute);
  app.use("/api/v1/regulator", regulatorRoute);
  app.use("/api/v1/chemical", auth, chemicalRoute);
  app.use("/api/v1/riskLevel", riskLevelRoute);
  app.use("/api/v1/residualRisk", residualRiskRoute);
  app.use("/api/v1/staff", auth, staffRoute);
  app.use("/api/v1/state", stateRoute);
  app.use("/api/v1/stripe", stripeAPIRoute);
  app.use("/api/v1/ourWork", ourWorkRoute);
  app.use("/api/v1/socialMedia", socialMediaRoute);
  app.use("/api/v1/toolbox", toolboxRoute);
  app.use("/api/v1/meetingMinutes", meetingMinutesRoute); // meeting minutes
  app.use("/api/v1/siteInspection", siteInspectionRoute);
  app.use("/api/v1/vehicleInspection", vehicleInspectionRoute);  //vehicle inspection
  app.use("/api/v1/hazard", hazardRoute);
  app.use("/api/v1/incidentForm", incidentFormRoute);
  app.use("/api/v1/changesMade", auth, changesMadeRoute);
  app.use("/api/v1/natureOfIncident", auth, natureOfIncidentRoute);
  app.use("/api/v1/rootcauseOfIncident", auth, rootcauseOfIncidentRoute);
  app.use("/api/v1/typeOfIncident", auth, typeOfIncidentRoute);
  app.use("/api/v1/manager", auth, managerRoute);
  app.use("/api/v1/WHSManager", auth, WHSManagerRoute);
  app.use("/api/v1/siteInspectionCategory", auth, siteInspectionCategoryRoute);
  app.use("/api/v1/siteInspectionTopic", siteInspectionTopicRoute);
  app.use("/api/v1/hazardTreatmentRelation", auth, hazardTreatmentRelationRoute);
  app.use("/api/v1/riskAssessment", riskAssessmentRoute);
  app.use("/api/v1/role", roleRoute);
  app.use("/api/v1/access", accessRoute);
  app.use("/api/v1/submittedDynamicForm", submittedDynamicFormRoute);
  app.use("/api/v1/savedForms", savedFormsRoute);
  app.use("/api/v1/savedDynamicForm", savedDynamicFormRoute);
  app.use("/api/v1/formCategory", auth, formCategoryRoute);
  app.use("/api/v1/accidentReportInstruction", auth, accidentReportInstructionRoute);
  app.use("/api/v1/riskAsstInstruction", riskAsstInstructionRoute);
  app.use("/api/v1/subContractor", subContractorRoute);
  app.use("/api/v1/termsAndCondition", termsAndConditionRoute);
  app.use("/api/v1/plantReturn", plantReturnRoute);
  app.use("/api/v1/ppeReturn", ppeReturnRoute);
  app.use("/api/v1/sendMail", sendMailRoute);
  app.use("/api/v1/logicalFormFrequency", logicalFormFrequencyRoute);
  app.use("/api/v1/registrationlnCms", registrationlnCmsRoute);
  app.use("/api/v1/subscriptionCms", subscriptionCmsRoute);
  app.use("/api/v1/dashboard", dashboardRoute);
  app.use("/api/v1/notification", notificationRoute);
  app.use("/api/v1/department", departmentRoute);
  app.use("/api/v1/items", itemsRoute);
  app.use("/api/v1/branch", branchRoute);
  app.use("/api/v1/riskAssessmentFormSetting",auth,formSetting)
};
